### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by rderania** [bszcz/fortran#2]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with fortran. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable fortran on @Sourcegraph by going to https://sourcegraph.com/github.com/bszcz/fortran and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by bszcz** [comment]
Done. However...

> Probably unsupported. Sourcegraph doesn't support FORTRAN, which appears to be this repository's primary language. The supported languages are Python, Go, Ruby, and JavaScript (node.js with package.json only). To attempt to use Sourcegraph's code browsing and code review features on this repository anyway, enable this repository.

Hence, only code browsing and code review features are enabled on this repository for now.
